### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.7/site-packages/LsBook-1.0.4-py3.7.egg/LsBook/assets/i18n/en.json'

### ISSUE THREAD

**Issue by noobcoderr** [liushilive/LsBook#1]
## 背景
python版本：3.7
系统:mac catalina 10.15.1
编译器:Pycharm
## 问题 
我先使用 pip3 install lsbook
然后再gitclone本项目到本地，
执行python setup.py build和install
最后cd到 test/test_book/目录下，执行lsbook -b 
得到以下错误
```
zhangjie@zhangjiedeMacBook-Pro test_book % lsbook -b 
2020-03-07 14:56:52,816 INFO:开始生成书籍
2020-03-07 14:56:52,817 INFO:书籍目录：/Users/zhangjie/Common/git/LsBook/tests/test_book
2020-03-07 14:56:52,818 INFO:输出目录：/Users/zhangjie/Common/git/LsBook/tests/test_book/_book
2020-03-07 14:56:52,818 ERROR:语言配置错误，使用默认语言：zh-cn
Traceback (most recent call last):
  File "/usr/local/bin/lsbook", line 11, in <module>
    load_entry_point('LsBook==1.0.4', 'console_scripts', 'lsbook')()
  File "/usr/local/lib/python3.7/site-packages/LsBook-1.0.4-py3.7.egg/LsBook/lsbook.py", line 60, in main
  File "/usr/local/lib/python3.7/site-packages/LsBook-1.0.4-py3.7.egg/LsBook/output/generateBook.py", line 26, in generateBook
  File "/usr/local/lib/python3.7/site-packages/LsBook-1.0.4-py3.7.egg/LsBook/parse/parse_config.py", line 24, in is_config_exist
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.7/site-packages/LsBook-1.0.4-py3.7.egg/LsBook/assets/i18n/en.json'
```
但是我看该egg包已经在该目录下了啊
```
zhangjie@zhangjiedeMacBook-Pro site-packages % pwd
/usr/local/lib/python3.7/site-packages
zhangjie@zhangjiedeMacBook-Pro site-packages % ls
APScheduler-3.6.3.dist-info             envparse-0.2.0.dist-info                pyrsistent-0.15.6.dist-info
LsBook-1.0.4-py3.7.egg                  envparse.py                             python_dateutil-2.6.1.dist-info
PyJWT-1.7.1.dist-info                   exotel                                  python_magic-0.4.15.dist-info
PySocks-1.7.1.dist-info                 exotel-0.1.5.dist-info                  pytz
```
请问我是哪儿出现了问题？我该怎么解决？谢谢

**Comment by liushilive** [comment]
* 更新 lsbook

  ```cmd
  pip3 install  -U lsbook
  ```

* gitclone https://github.com/liushilive/github_software_testing_dictionary.git 项目
* 进入目录，执行 `lsbook -b`

你将得到实例。
